name: Labeler
on: [pull_request]

jobs:
  testLabel:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/workflow/face.yml
